[package]
name = "sopt"
version = "0.1.0"
authors = ["Brethland Yang <brethland@gmail.com>"]
edition = "2018"

[lib]
name = "sopt"
proc-macro = true

[features]

default = ["email-restriction"]
email-restriction = []

[dependencies]
# actix stuff
actix-web = "3.3.2"
actix-identity = "*"
actix-multipart = "0.3.0"

# low version of tokio
deadpool-redis = "0.5.0"
sqlx = { version = "0.4.1", features = [ "postgres", "runtime-actix-native-tls", "chrono", "json" ] }

#serde related
serde = { version = "^1.0", features = ["derive"] }
serde_bencode = "*"
serde_bytes = "*"
serde_json = "*"

# utils
futures = "0.3.13"
dotenv = "0.15.0"
config = "0.10.1"
derive_more = "0.99.11"
env_logger = "*"
pest = "^2.1.3"
pest_derive = "^2.1.0"
lettre = "0.10.0-alpha.4"
hex = "0.4.2"
base64 = "0.13.0"
syn = "*"
sanitize-filename = "0.3.0"
chrono = { version = "0.4.19", features = ["serde"] }

# crypto related
sha2 = "^0.9"
rand = "0.8.3"
rust-argon2 = "0.8"
