[package]
name = "sopt"
version = "0.1.0"
authors = ["Brethland Yang <brethland@gmail.com>"]
edition = "2018"

[dependencies]
# actix stuff
#actix-web = "4.0.0-beta.3"
actix-web = "3.3.2"
actix-identity = "*"

# low version of tokio
deadpool-redis = "0.5.0"
sqlx = { version = "0.5.1", features = [ "postgres", "runtime-actix-native-tls" ] }

#serde related
serde = { version = "^1.0", features = ["derive"] }
serde_bencode = "*"
serde_bytes = "*"

# utils
dotenv = "0.15.0"
config = "0.10.1"
derive_more = "0.99.11"
env_logger = "*"
pest = "^2.1.3"
pest_derive = "^2.1.0"
lettre = "0.10.0-alpha.4"

# crypto related
sha2 = "^0.9"
rand = "0.8.3"
rust-argon2 = "0.8"
