name: CI
on: [push]
jobs:
  testing:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_DB: sopt
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: password
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      redis:
        image: redis:buster
        ports:
          - 6379:6379

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cp .env.example .env
      - run: cargo install sqlx-cli
      - run: sqlx migrate run
      - run: PGPASSWORD=password psql -h localhost -U postgres -d sopt -f rank.sql
      - run: cargo test

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable

      - run: cargo clippy -- -D clippy::all